### ISSUE TITLE
Restarting the cluster

### ISSUE THREAD

**Issue by drorata** [maxyermayank/docker-compose-elasticsearch-kibana#1]
First, thanks for sharing this helpful compose!

After shutting down the cluster and restarting it, it happens (not always) that one of the ES nodes doesn't go up, and in turn the kibana nodes (which seems to always go up) doesn't find the cluster. Have you experienced something of that sort? Is there some "right" way to turn off the cluster?

**Comment by tp** [comment]
I think the same thing happened to me.

On the first day it was working just fine, and then after a restart of Docker (for macOS) it doesn't work anymore:

```
kibana            | {"type":"log","@timestamp":"2018-12-04T13:18:28Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana            | {"type":"log","@timestamp":"2018-12-04T13:18:28Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana            | {"type":"log","@timestamp":"2018-12-04T13:18:30Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
```

@drorata Did you find a solution? Since I removed the old containers and the script doesn't seem to use any files form disk I am not sure why it wouldn't just start up like on the first day.

**Comment by drorata** [comment]
@tp Sorry, but I cannot recall how I worked around it.
